### ISSUE TITLE
カスタム列「画像」で画像が添付できないことがある

### ISSUE THREAD

**Issue by tkpontas** [exceedone/exment#1043]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
カスタム列の種類が「画像」になっているカスタム列を含んだフォームで
編集・新規作成を問わずに数MBの画像を添付して保存しようとすると、写真を添付してくださいのエラーが出て保存できない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
テーブル問わず、カスタム列の種類が「画像」のカスタム列を作成。
適当なフォームを作成し、作成した画像のカスタム列を配置。
フォーム編集画面で画像を添付（数MB）
保存を実行すると「写真を添付してください」のエラー表示

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Ver.4.2.2

Ver.4.2.1では発生しませんでした。

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

[2021-08-20 13:51:20] local.ERROR: Use of undefined constant BLOBs - assumed 'BLOBs' (this will throw an Error in a future version of PHP) (SQL: select * from `custom_tables` order by `order` asc, `id` asc) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): Use of undefined constant BLOBs - assumed 'BLOBs' (this will throw an Error in a future version of PHP) (SQL: select * from `custom_tables` order by `order` asc, `id` asc) at home/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
[stacktrace]
#0 home/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 home/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 home/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 home/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2147): Illuminate\\Database\\Query\\Builder->runSelect()
#4 home/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2619): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 home/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2148): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 home/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(546): Illuminate\\Database\\Query\\Builder->get(Array)
#7 home/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(530): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 home/vendor/exceedone/exment/src/Model/Traits/UseRequestSessionTrait.php(61): Illuminate\\Database\\Eloquent\\Builder->get()
#9 home/vendor/exceedone/exment/src/Model/System.php(210): Exceedone\\Exment\\Model\\CustomTable::Exceedone\\Exment\\Model\\Traits\\{closure}()
#10 home/vendor/exceedone/exment/src/Model/Traits/UseRequestSessionTrait.php(62): Exceedone\\Exment\\Model\\System::cache('all_records_cus...', Object(Closure))
#11 home/vendor/exceedone/exment/src/Model/Traits/UseRequestSessionTrait.php(40): Exceedone\\Exment\\Model\\CustomTable::_allRecords('cache', Object(Closure), true, Array, true)
#12 home/vendor/exceedone/exment/src/Model/CustomTable.php(1129): Exceedone\\Exment\\Model\\CustomTable::firstRecordCache(Object(Closure))
#13 home/vendor/exceedone/exment/src/Model/CustomTable.php(1013): Exceedone\\Exment\\Model\\CustomTable::getEloquent('involved_record')
#14 home/vendor/exceedone/exment/src/ExmentServiceProvider.php(333): Exceedone\\Exment\\Model\\CustomTable::findByEndpoint()
#15 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Exceedone\\Exment\\ExmentServiceProvider->Exceedone\\Exment\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#16 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#17 home/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve('Exceedone\\\\Exmen...', Array, true)
#18 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve('Exceedone\\\\Exmen...', Array)
#19 home/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make('Exceedone\\\\Exmen...', Array)
#20 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make('Exceedone\\\\Exmen...')
#21 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#22 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#23 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('Exceedone\\\\Exmen...')
#24 home/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve('Exceedone\\\\Exmen...', Array, true)
#25 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve('Exceedone\\\\Exmen...', Array)
#26 home/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make('Exceedone\\\\Exmen...', Array)
#27 home/vendor/laravel/framework/src/Illuminate/Routing/Route.php(233): Illuminate\\Foundation\\Application->make('Exceedone\\\\Exmen...')
#28 home/vendor/laravel/framework/src/Illuminate/Routing/Route.php(833): Illuminate\\Routing\\Route->getController()
#29 home/vendor/laravel/framework/src/Illuminate/Routing/Route.php(794): Illuminate\\Routing\\Route->controllerMiddleware()
#30 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Routing\\Route->gatherMiddleware()
#31 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#32 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#33 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#34 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#35 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#36 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#37 home/vendor/exceedone/exment/src/Middleware/ExmentDebug.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Exceedone\\Exment\\Middleware\\ExmentDebug->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 home/vendor/exceedone/exment/src/Middleware/TrustProxies.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Exceedone\\Exment\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 home/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#53 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#54 home/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#55 {main}

[previous exception] [object] (ErrorException(code: 0): Use of undefined constant BLOBs - assumed 'BLOBs' (this will throw an Error in a future version of PHP) at home/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:109)
[stacktrace]
#0 home/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(109): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Use of undefine...', '/home/stmweb/mt...', 109, Array)
#1 home/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(57): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#2 home/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(30): Illuminate\\Database\\Connectors\\MySqlConnector->configureEncoding(Object(Doctrine\\DBAL\\Driver\\PDOConnection), Array)
#3 home/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 home/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func(Object(Closure))
#6 home/vendor/laravel/framework/src/Illuminate/Database/Connection.php(959): Illuminate\\Database\\Connection->getPdo()
#7 home/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\\Database\\Connection->getReadPdo()
#8 home/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Illuminate\\Database\\Connection->getPdoForSelect(true)
#9 home/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)
#10 home/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#11 home/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#12 home/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#13 home/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2147): Illuminate\\Database\\Query\\Builder->runSelect()
#14 home/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2619): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#15 home/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2148): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#16 home/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(546): Illuminate\\Database\\Query\\Builder->get(Array)
#17 home/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(530): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#18 home/vendor/exceedone/exment/src/Model/Traits/UseRequestSessionTrait.php(61): Illuminate\\Database\\Eloquent\\Builder->get()
#19 home/vendor/exceedone/exment/src/Model/System.php(210): Exceedone\\Exment\\Model\\CustomTable::Exceedone\\Exment\\Model\\Traits\\{closure}()
#20 home/vendor/exceedone/exment/src/Model/Traits/UseRequestSessionTrait.php(62): Exceedone\\Exment\\Model\\System::cache('all_records_cus...', Object(Closure))
#21 home/vendor/exceedone/exment/src/Model/Traits/UseRequestSessionTrait.php(40): Exceedone\\Exment\\Model\\CustomTable::_allRecords('cache', Object(Closure), true, Array, true)
#22 home/vendor/exceedone/exment/src/Model/CustomTable.php(1129): Exceedone\\Exment\\Model\\CustomTable::firstRecordCache(Object(Closure))
#23 home/vendor/exceedone/exment/src/Model/CustomTable.php(1013): Exceedone\\Exment\\Model\\CustomTable::getEloquent('involved_record')
#24 home/vendor/exceedone/exment/src/ExmentServiceProvider.php(333): Exceedone\\Exment\\Model\\CustomTable::findByEndpoint()
#25 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Exceedone\\Exment\\ExmentServiceProvider->Exceedone\\Exment\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#26 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#27 home/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve('Exceedone\\\\Exmen...', Array, true)
#28 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve('Exceedone\\\\Exmen...', Array)
#29 home/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make('Exceedone\\\\Exmen...', Array)
#30 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make('Exceedone\\\\Exmen...')
#31 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#32 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#33 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('Exceedone\\\\Exmen...')
#34 home/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve('Exceedone\\\\Exmen...', Array, true)
#35 home/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve('Exceedone\\\\Exmen...', Array)
#36 home/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make('Exceedone\\\\Exmen...', Array)
#37 home/vendor/laravel/framework/src/Illuminate/Routing/Route.php(233): Illuminate\\Foundation\\Application->make('Exceedone\\\\Exmen...')
#38 home/vendor/laravel/framework/src/Illuminate/Routing/Route.php(833): Illuminate\\Routing\\Route->getController()
#39 home/vendor/laravel/framework/src/Illuminate/Routing/Route.php(794): Illuminate\\Routing\\Route->controllerMiddleware()
#40 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Routing\\Route->gatherMiddleware()
#41 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#42 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#43 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#44 home/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#45 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#46 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#47 home/vendor/exceedone/exment/src/Middleware/ExmentDebug.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Exceedone\\Exment\\Middleware\\ExmentDebug->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 home/vendor/exceedone/exment/src/Middleware/TrustProxies.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Exceedone\\Exment\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 home/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 home/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#63 home/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#64 home/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#65 {main}
"} 

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![image](https://user-images.githubusercontent.com/60683813/130186164-0b2f8f5c-8b66-4ba0-91eb-a702d9d78c99.png)
編集画面画像添付時

![image](https://user-images.githubusercontent.com/60683813/130186244-6b75219f-6e3f-44a3-b582-4f75d3d8bdc7.png)
保存ボタンをクリック時

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
カスタム列の種類が「画像」であれば、外部公開フォームでも同様の現象が発生。
複数枚添付の有無は関係ない様子。またファイル（添付）形式であれば特に問題は発生していない模様。

**Comment by tkpontas** [comment]
原因が判明しました。拡張子が大文字のJPGだったので画像として認識していないようでした。データベース云々は別のエラーのようです。2度もお騒がせしました。
