### ISSUE TITLE
[Call to a member function getValue() on null]サーチモーダルを開いたときにエラー

### ISSUE THREAD

**Issue by tkpontas** [exceedone/exment#1209]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
サーチモーダルでCall to a member function getValue() on nullのエラーが表示されて選択できない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

エキスパートモード有効
4つのテーブルを作成

テーブルA（指示書）
　カスタム列：　指示書番号

テーブルB（案件管理）
　カスタム列：　指示書番号（テーブルA/他のテーブルから参照）

テーブルC（関係者）
　テーブルBを親とする1：多リレーション（インポート時：指示書番号/エクスポート時：指示書番号）

テーブルD（対応記録）
　カスタム列：　関係者（テーブルC/他のテーブルから参照）

テーブルCにおいて、フィルタ検索項目にテーブルBのカスタム列を追加（例→案件管理：指示書番号）
テーブルDにおいて、見出しのフォーマットにテーブルBのカスタム列をparentとするパラメータ変数を使用

テーブルDにおいて、カスタム列：関係者（テーブルC/他のテーブルから参照）を選択
　→　直接選択時、検索絞り込みは問題なし
　→　サーチをクリックして、サーチモーダルを表示させると、モーダル内画面に
　　　Call to a member function getValue() on nullのエラーが表示される。

　※　テーブルCにおいてフィルタ検索項目からテーブルBのカスタム列をすべて削除すると正常動作する。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Ver.5.0.0
Coreserver CORE-Xプラン

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

[2022-08-01 14:28:35] local.ERROR: Call to a member function getValue() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function getValue() on null at /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Services/ReplaceFormat/Items/ParentValue.php:39)
[stacktrace]
#0 [internal function]: Exceedone\\Exment\\Services\\ReplaceFormat\\Items\\ParentValue->Exceedone\\Exment\\Services\\ReplaceFormat\\Items\\{closure}()
#1 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map()
#2 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(719): Illuminate\\Support\\Arr::map()
#3 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Services/ReplaceFormat/Items/ParentValue.php(40): Illuminate\\Support\\Collection->map()
#4 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Services/ReplaceFormat/ReplaceFormatService.php(90): Exceedone\\Exment\\Services\\ReplaceFormat\\Items\\ParentValue->replace()
#5 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Services/Helpers.php(1459): Exceedone\\Exment\\Services\\ReplaceFormat\\ReplaceFormatService::replaceTextFromFormat()
#6 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Model/CustomValue.php(1175): replaceTextFromFormat()
#7 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Model/CustomValue.php(1120): Exceedone\\Exment\\Model\\CustomValue->getExpansionLabel()
#8 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/DataItems/Grid/DefaultGrid.php(689): Exceedone\\Exment\\Model\\CustomValue->getLabel()
#9 [internal function]: Exceedone\\Exment\\DataItems\\Grid\\DefaultGrid->Exceedone\\Exment\\DataItems\\Grid\\{closure}()
#10 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/laravel-admin/src/Grid/Column.php(812): call_user_func_array()
#11 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/laravel-admin/src/Grid/Column.php(874): Encore\\Admin\\Grid\\Column->callDisplayCallbacks()
#12 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/laravel-admin/src/Grid.php(656): Encore\\Admin\\Grid\\Column->fill()
#13 [internal function]: Encore\\Admin\\Grid->Encore\\Admin\\{closure}()
#14 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map()
#15 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(719): Illuminate\\Support\\Arr::map()
#16 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/laravel-admin/src/Grid.php(659): Illuminate\\Support\\Collection->map()
#17 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/laravel-admin/src/Grid.php(1087): Encore\\Admin\\Grid->build()
#18 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/DataItems/Grid/DefaultGrid.php(673): Encore\\Admin\\Grid->render()
#19 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Controllers/CustomValueController.php(225): Exceedone\\Exment\\DataItems\\Grid\\DefaultGrid->renderModal()
#20 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Controllers/AdminControllerTableBase.php(54): Exceedone\\Exment\\Controllers\\CustomValueController->index()
#21 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Exceedone\\Exment\\Controllers\\AdminControllerTableBase->callAction()
#22 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#23 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#24 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#25 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#26 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/laravel-admin/src/Middleware/Session.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\\Admin\\Middleware\\Session->handle()
#28 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\\Admin\\Middleware\\Permission->handle()
#30 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\\Admin\\Middleware\\Bootstrap->handle()
#32 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\LogOperation->handle()
#34 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\\Admin\\Middleware\\Pjax->handle()
#36 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/Bootstrap.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Bootstrap->handle()
#38 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Morph->handle()
#40 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\AuthenticatePasswordLimit->handle()
#42 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Authenticate2factor->handle()
#44 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/Authenticate.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Authenticate->handle()
#46 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/Initialize.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Initialize->handle()
#48 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\\Exment\\Middleware\\IpFilterBase->handleBase()
#50 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\WebIPFilter->handle()
#51 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/Browser.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Browser->handle()
#53 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#55 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#57 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#59 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#61 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#62 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#64 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#66 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#68 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#69 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#70 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#71 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#72 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#73 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/ExmentDebug.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\ExmentDebug->handle()
#75 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/exceedone/exment/src/Middleware/TrustProxies.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\TrustProxies->handle()
#77 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#79 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#80 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#82 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#83 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#84 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#85 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#87 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#89 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#91 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#93 /home/hogehoge/domains/hogehoge.com/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#94 /home/hogehoge/domains/hogehoge.com/laravel/exment/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#95 {main}
"} 

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
省略

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
不具合では無く仕様の可能性もありますが、エラーログが出ていたので不具合報告させていただきました。

**Comment by tkpontas** [comment]
Ver.5.0.3にバージョンアップしたら解消されましたのでクローズします。
