### ISSUE TITLE
ラジオボタン形式のカスタム列が一覧画面からデータ更新できない

### ISSUE THREAD

**Issue by a0z0** [exceedone/exment#1250]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

ラジオボタン形式のカスタム列をデータ更新設定「一覧画面のチェックボタン選択時」で更新しようとすると
入力ダイアログででServer Errorが発生する

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

1. 選択肢&ラジオボタン形式のカスタム列を作成
2. データ更新設定「一覧画面のチェックボタン選択時」で1.の列を「入力ダイアログ設定」に追加
3. 一覧画面からデータ更新操作 -> Server Error

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

[2022-12-09 16:27:11] local.ERROR: Method Exceedone\Exment\Form\Field\RadioButton::asModal does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Exceedone\\Exment\\Form\\Field\\RadioButton::asModal does not exist. at /var/www/exment/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113)
[stacktrace]
#0 /var/www/exment/vendor/exceedone/exment/src/ColumnItems/CustomColumns/Select.php(98): Encore\\Admin\\Form\\Field->__call()
#1 /var/www/exment/vendor/exceedone/exment/src/ColumnItems/CustomItem.php(449): Exceedone\\Exment\\ColumnItems\\CustomColumns\\Select->setAdminOptions()
#2 /var/www/exment/vendor/exceedone/exment/src/ColumnItems/CustomItem.php(438): Exceedone\\Exment\\ColumnItems\\CustomItem->getCustomField()
#3 /var/www/exment/vendor/exceedone/exment/src/Services/FormHelper.php(65): Exceedone\\Exment\\ColumnItems\\CustomItem->getAdminField()
#4 /var/www/exment/vendor/exceedone/exment/src/Controllers/CustomValueController.php(759): Exceedone\\Exment\\Services\\FormHelper::getFormFieldObj()
#5 /var/www/exment/vendor/exceedone/exment/src/Controllers/AdminControllerTableBase.php(54): Exceedone\\Exment\\Controllers\\CustomValueController->operationModal()
#6 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Exceedone\\Exment\\Controllers\\AdminControllerTableBase->callAction()
#7 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#9 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#10 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Session.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\\Admin\\Middleware\\Session->handle()
#13 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\\Admin\\Middleware\\Permission->handle()
#15 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\\Admin\\Middleware\\Bootstrap->handle()
#17 /var/www/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\LogOperation->handle()
#19 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\\Admin\\Middleware\\Pjax->handle()
#21 /var/www/exment/vendor/exceedone/exment/src/Middleware/Bootstrap.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Bootstrap->handle()
#23 /var/www/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Morph->handle()
#25 /var/www/exment/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\AuthenticatePasswordLimit->handle()
#27 /var/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Authenticate2factor->handle()
#29 /var/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Authenticate->handle()
#31 /var/www/exment/vendor/exceedone/exment/src/Middleware/Initialize.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Initialize->handle()
#33 /var/www/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\\Exment\\Middleware\\IpFilterBase->handleBase()
#35 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\WebIPFilter->handle()
#36 /var/www/exment/vendor/exceedone/exment/src/Middleware/Browser.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\Browser->handle()
#38 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#40 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#42 /var/www/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#44 /var/www/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#46 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#47 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#49 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#51 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#53 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#54 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#55 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#56 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#57 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#58 /var/www/exment/vendor/exceedone/exment/src/Middleware/ExmentDebug.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\ExmentDebug->handle()
#60 /var/www/exment/vendor/exceedone/exment/src/Middleware/TrustProxies.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\\Exment\\Middleware\\TrustProxies->handle()
#62 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#64 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#65 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#67 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#68 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#70 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#72 /var/www/exment/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#74 /var/www/exment/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#76 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#78 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#79 /var/www/exment/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#80 {main}
"}

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by a0z0** [comment]
v5.0.5で改善されておりましたのでクローズします。
ありがとうございました。
