### ISSUE TITLE
フィルタ検索でSQLエラーが発生する場合があります

### ISSUE THREAD

**Issue by KiyokazuTakeuchi** [exceedone/exment#1428]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

フィルタ検索で選択肢(項目)を指定しサーチボタンを押すとSQLエラー（添付画面）が表示される。
尚、選択する項目によってはエラーが発生しない場合もある。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

テーブルをビューで表示させ，フィルタボタンを押した後，ビューの項目を指定しサーチボタンを押すとSQLエラーとなる。
他のビューでも同じような現象が複数発生する。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

Version v5.0.6

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

 local.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column '9f03d97dd099f980b43c.column_0e836d0c25f59f3e5e79' in 'where clause' in /mnt/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /mnt/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute()
#1 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(419): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#4 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\Database\Connection->run()
#5 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2706): Illuminate\Database\Connection->select()
#6 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\Database\Query\Builder->runSelect()
#7 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#8 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2695): Illuminate\Database\Query\Builder->onceWithColumns()
#9 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2844): Illuminate\Database\Query\Builder->get()
#10 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2803): Illuminate\Database\Query\Builder->runPaginationCountQuery()
#11 /mnt/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(891): Illuminate\Database\Query\Builder->getCountForPagination()
#12 [internal function]: Illuminate\Database\Eloquent\Builder->paginate()
#13 /mnt/exment/vendor/exceedone/laravel-admin/src/Grid/Model.php(459): call_user_func_array()
#14 /mnt/exment/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(235): Encore\Admin\Grid\Model->Encore\Admin\Grid\{closure}()
#15 /mnt/exment/vendor/exceedone/laravel-admin/src/Grid/Model.php(461): Illuminate\Support\Collection->each()
#16 /mnt/exment/vendor/exceedone/laravel-admin/src/Grid/Model.php(364): Encore\Admin\Grid\Model->get()
#17 /mnt/exment/vendor/exceedone/laravel-admin/src/Grid/Filter.php(547): Encore\Admin\Grid\Model->buildData()
#18 /mnt/exment/vendor/exceedone/laravel-admin/src/Grid/Concerns/HasFilter.php(65): Encore\Admin\Grid\Filter->execute()
#19 /mnt/exment/vendor/exceedone/laravel-admin/src/Grid.php(643): Encore\Admin\Grid->applyFilter()
#20 /mnt/exment/vendor/exceedone/laravel-admin/src/Grid.php(1087): Encore\Admin\Grid->build()
#21 /mnt/exment/vendor/exceedone/laravel-admin/src/Layout/Column.php(93): Encore\Admin\Grid->render()
#22 /mnt/exment/vendor/exceedone/laravel-admin/src/Layout/Row.php(116): Encore\Admin\Layout\Column->build()
#23 /mnt/exment/vendor/exceedone/laravel-admin/src/Layout/Content.php(223): Encore\Admin\Layout\Row->build()
#24 /mnt/exment/vendor/exceedone/laravel-admin/src/Layout/Content.php(305): Encore\Admin\Layout\Content->build()
#25 /mnt/exment/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Encore\Admin\Layout\Content->render()
#26 /mnt/exment/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent()
#27 /mnt/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(906): Illuminate\Http\Response->__construct()
#28 /mnt/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(875): Illuminate\Routing\Router::toResponse()
#29 /mnt/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Router->prepareResponse()
#30 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#31 /mnt/exment/vendor/exceedone/laravel-admin/src/Middleware/Session.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Session->handle()
#33 /mnt/exment/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Permission->handle()
#35 /mnt/exment/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Bootstrap->handle()
#37 /mnt/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\LogOperation->handle()
#39 /mnt/exment/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Pjax->handle()
#41 /mnt/exment/vendor/exceedone/exment/src/Middleware/Bootstrap.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Bootstrap->handle()
#43 /mnt/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Morph->handle()
#45 /mnt/exment/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\AuthenticatePasswordLimit->handle()
#47 /mnt/exment/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Authenticate2factor->handle()
#49 /mnt/exment/vendor/exceedone/exment/src/Middleware/Authenticate.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Authenticate->handle()
#51 /mnt/exment/vendor/exceedone/exment/src/Middleware/Initialize.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Initialize->handle()
#53 /mnt/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /mnt/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\Exment\Middleware\IpFilterBase->handleBase()
#55 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\WebIPFilter->handle()
#56 /mnt/exment/vendor/exceedone/exment/src/Middleware/Browser.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Browser->handle()
#58 /mnt/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#60 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#62 /mnt/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#64 /mnt/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 /mnt/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#66 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#67 /mnt/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#68 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#69 /mnt/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#71 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#72 /mnt/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Pipeline\Pipeline->then()
#73 /mnt/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack()
#74 /mnt/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute()
#75 /mnt/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\Routing\Router->dispatchToRoute()
#76 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router->dispatch()
#77 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#78 /mnt/exment/vendor/exceedone/exment/src/Middleware/ExmentDebug.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#79 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\ExmentDebug->handle()
#80 /mnt/exment/vendor/exceedone/exment/src/Middleware/TrustProxies.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#81 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\TrustProxies->handle()
#82 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#83 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#84 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#85 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#86 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#87 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#88 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#89 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#90 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#91 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#92 /mnt/exment/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#93 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
#94 /mnt/exment/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#95 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#96 /mnt/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#97 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#98 /mnt/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#99 /mnt/exment/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#100 {main}

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

![sql_error](https://github.com/exceedone/exment/assets/26865439/13bfb7de-0cf4-4010-8408-7aeb3dc8ca01)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

[#1233](https://github.com/exceedone/exment/issues/1233)と同件と考えます。

**Comment by a0z0** [comment]
こんにちは。
同じかどうかわからないですけど自分のケースだと、
ビューの設定でデータ並べ替えを指定してるとフィルターでエラーになったので、データ並べ替えをやめました。
