### ISSUE TITLE
API 使用できない The authorization grant type is not supported by the authorization server.

### ISSUE THREAD

**Issue by eliaya** [exceedone/exment#1490]
### Describe the bug / バグの説明
アップグレードして v6.x バージョンになると、API が使用できなくなりました。
同様に異なるサーバー環境で構築してみましたが、新しいExment v6.1.0 を再インストールしても結果は同じでした。

### To Reproduce / 再現手順
curl と Postman を別々使用してテストを行いました。[Exmentマニュアル](https://exment.net/docs/#/ja/api?id=api%e8%a8%ad%e5%ae%9a)の API 説明に基づいて、grant_type に `password`、`authorization_code`、および `api_key` をそれぞれ試しましたが、同じ結果が返されました。

```
curl -XPOST -H 'client_id: 8a260330-46a7-11ef-940b-f7d6776effea' -H 'client_secret: S694tRO5LRaS5G2NNU7TE7ER3VzSJSme9oySF70x' -H 'api_key: key_dpmqhSHm1dj7RfTUnenVOOngxlUTaB' -H 'grant_type: api_key' -H "Content-type: application/json" 'http://localhost:8082/admin/oauth/token'
```
### Version / 発生バージョン
- Exment v6.0.4
- Exment v6.1.0

### Error log / エラーログ
**storage/logs/laravel.log**
```
[previous exception] [object] (League\\OAuth2\\Server\\Exception\\OAuthServerException(code: 2): The authorization grant type is not supported by the authorization server. at /var/www/html/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:124)
[stacktrace]
#0 /var/www/html/vendor/league/oauth2-server/src/AuthorizationServer.php(212): League\\OAuth2\\Server\\Exception\\OAuthServerException::unsupportedGrantType()
#1 /var/www/html/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(52): League\\OAuth2\\Server\\AuthorizationServer->respondToAccessTokenRequest(Object(Nyholm\\Psr7\\ServerRequest), Object(Nyholm\\Psr7\\Response))
```
**Return response**
```
{"message":"The authorization grant type is not supported by the authorization server."}
```

### Screenshots / スクリーンショット
![SCR-20240721-pqvp](https://github.com/user-attachments/assets/54e835ec-7b19-4376-b73c-7db3ded1dd00)

### Additional context / その他  
**サーバー環境**
- Web Server:Nginx/1.27.0
- PHP: 8.2-fpm
- DB: MariaDB v11.0

大体 バージョン v4.x の時に Exment API を使用したことがあり、正常に使えたと記憶しています。最近 v6.x にアップグレードした後、このような問題に直面しています。私が何か手順を間違えたのでしょうか？　お願いします

**Comment by KajitoriAdmin** [comment]
@eliaya 

v5.x以降の場合は、以下のManualに従って実装する必要があります。
https://exment.net/docs/#/ja/api?id=%e7%8b%ac%e8%87%aa%e3%81%a7%e9%96%8b%e7%99%ba%e3%81%99%e3%82%8b%e3%83%97%e3%83%ad%e3%82%b0%e3%83%a9%e3%83%a0%e5%81%b4%e3%81%ae%e5%ae%9f%e8%a3%85-1
そのため、以下の実装方法で試していただけませんか？

curl --location 'http://localhost:8082/admin/oauth/token' \
--header 'Content-Type: application/json' \
--data '{
    "grant_type": "api_key",
    "client_id": "8a260330-46a7-11ef-940b-f7d6776effea",
    "client_secret": "S694tRO5LRaS5G2NNU7TE7ER3VzSJSme9oySF70x",
    "api_key": "key_dpmqhSHm1dj7RfTUnenVOOngxlUTaB",
    "scope": "value_write"
}'
※Scopeの箇所にて「value_write」を指定していますが、以下のScope一覧をご参照ください。
https://exment.net/docs/#/ja/api?id=%e3%82%b9%e3%82%b3%e3%83%bc%e3%83%97%e4%b8%80%e8%a6%a7

**Comment by eliaya** [comment]
@KajitoriAdmin 
返信ありがとうございます！

このような試してみましたが、残念ながら、curl と Postman のどちらを使用しても同じ問題が発生します。

## curl via macOS ZSH Shell
```bash
❯ curl -XPOST -H 'client_id: 8a260330-46a7-11ef-940b-f7d6776effea' -H 'client_secret: S694tRO5LRaS5G2NNU7TE7ER3VzSJSme9oySF70x' -H 'api_key: key_dpmqhSHm1dj7RfTUnenVOOngxlUTaB' -H 'grant_type: api_key' -H 'scope: value_write' -H "Content-type: application/json" 'http://localhost:8082/admin/oauth/token'
{"message":"The authorization grant type is not supported by the authorization server."}%
```

## Postman
```bash
POST http://localhost:8082/admin/oauth/token
401
68 ms
POST /admin/oauth/token HTTP/1.1
Content-Type: application/json
grant_type: api_key
client_id: 525dffd0-482a-11ef-8d7f-07bcedb20dce
client_secret: l2GEM8edYG3XrVyU0hQ92Zafr7r7Pr9HqRAtk9yd
api_key: key_TOCsnoZc6LRVo40zqDznxdVDcxTk1F
scope: value_write
User-Agent: PostmanRuntime/7.37.3
Accept: */*
Postman-Token: 32ae8d92-0c3c-418e-962d-226ae399982e
Host: localhost:8082
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0
 
HTTP/1.1 401 Unauthorized
Server: nginx/1.27.0
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/8.2.21
Cache-Control: no-cache, private
Date: Mon, 22 Jul 2024 13:04:54 GMT
 
{"message":"The authorization grant type is not supported by the authorization server."}
```


Windows 11 、Linux Debian 12や macOS (Apple M2)で curl を試していたでも、同じ問題があります。


ちなみに、zsh や bash シェルでは実行できないようです。
しかし、これは問題の本質ではないので無視してください。
```bash
❯ curl --location 'http://localhost:8082/admin/oauth/token'
--header 'Content-Type: application/json'
--data '{
"grant_type": "api_key",
"client_id": "8a260330-46a7-11ef-940b-f7d6776effea",
"client_secret": "S694tRO5LRaS5G2NNU7TE7ER3VzSJSme9oySF70x",
"api_key": "key_dpmqhSHm1dj7RfTUnenVOOngxlUTaB",
"scope": "value_write"
}'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="robots" content="noindex,nofollow,noarchive" />
    <title>An Error Occurred: Method Not Allowed</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>❌</text></svg>" />
    <style>body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
.container { margin: 30px; max-width: 600px; }
h1 { color: #dc3545; font-size: 24px; }
h2 { font-size: 18px; }</style>
</head>
<body>
<div class="container">
    <h1>Oops! An Error Occurred</h1>
    <h2>The server returned a "405 Method Not Allowed".</h2>

    <p>
        Something is broken. Please let us know what you were doing when this error occurred.
        We will fix it as soon as possible. Sorry for any inconvenience caused.
    </p>
</div>
</body>
</html>zsh: command not found: --header
zsh: command not found: --data
```

**Comment by koizu-mkII** [comment]
@eliaya 
@KajitoriAdmin 
Windows10 DOSコマンドでのcurlの場合、以下のようにしたら正しくトークンが取得できました。
```
curl -X POST -H "Content-Type:application/json" --data "{\"grant_type\":\"password\",\"client_id\":\"cb54ce70-47a2-11ef-bf66-fb2119a8845e\",\"client_secret\":\"jdrxwaZtYrTQxNpRYVY2lmj4UbBdd2JzvGdFZfAi\",\"username\":\"api_user\",\"password\":\"xxxxxxxx\",\"scope\":\"me value_write\"}" http://localhost:8080/admin/oauth/token
{"token_type":"Bearer","expires_in":31536000,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJjYjU0Y2U3MC00N2EyLTExZWYtYmY2Ni1mYjIxMTlhODg0NWUiLCJqdGkiOiI1MDA1MGU2NzZlNGJlZDlhM2M2MDhhNmExYzc0OTkzYzc2NDRhYjcyMjI1ZTIzMTRlNWQ3OTFhMjFmZTlhMTMwY2QwOWNlNjczYTE1NGIyMiIsImlhdCI6MTcyMTcxODU1OC4yOTU4MSwibmJmIjoxNzIxNzE4NTU4LjI5NTgxNCwiZXhwIjoxNzUzMjU0NTU4LjI2MjEyNCwic3ViIjoiNSIsInNjb3BlcyI6WyJtZSIsInZhbHVlX3dyaXRlIl19.qZUOeBK8r2DG5N_khzjRi6c2F4QUHl5aJQlvocOxaHyZ5hEGEZ5k1RlDlyrIgN4LjpOhB_6rEFRATx0O5TVxCGMdRv8tptv-ld8VDNofdsoTEOS_RIsIdRkOYRl2SZuzDz5otC-NIYKECoIdRWdbLwKg8pwCvk_MBLvXxLYS-dLL5zFZnN6H3euAHgqLSXect94KlLFH41yL-XXaRow3MdbFZUTohZdGDFasGZAASC8IDQVe8zFp77YIgKq3MC2ZndyKtzRkybmUhIOoOjWKLtyAVOz4xZSRWdl4sf3HAIoTQQTU924n41xRAPavgOTAOVEK_SkmQJdDemfHwVmopiWhmR5RzN1Iij5EZ-Kg_KDNao8-7818DpN5zKrnFNqepsdIhpl_6dRP2YK2jT433ggS_kOGM3in4xDKRH3Nlviv0PqXPmd-z0p0hfaFXHukdzu4iaTwVZLwcmL5WEbR5UcG6FcKE8OeehZ8vTcjesJT2Gaxn4FK5dK2WiKbUMIrXrQVNBsx03_gL1lm0tKBJQp1-AUyyQYRXs2HKCDbc7rUrYF7IJ2S9iTIxjwBvEuAAI0d_zZ_NR28oIgoW3nC5vtwYd2KqCs0n78DEHQQXqSl6mZnjPKk2Fd2fQ8IX7OBq0ZaIhkoC-MFuOfkjmHVRMmD5VejAMOuMozZXLcxOX4","refresh_token":"def50200feae6c5e5e740361f5f94f34dcf84b6b7e54a9b646727d8da074582f48652c3292731311aaa169731b8cb91740b7383ba7ef95e0ba2a1934da8890fc6ab81a6031a20f27a12757e8f9509cc1962d9637fcaf93153700bd8e5f9a3eccb81412fa42c08b669e651a6c5b230ee3ff265257cc2c4d76ab8508b9f0bc7dee6e8df81db5c1945c9eece3fd33cfbf65e28b70c2e6ce35848bf1c0a3ab3a10ae63054ed682c5d0161f1ad311ca09901aa3d72a810757f89f58e23952482f717593782eaf11c35e99f81dd34e6ae231bdfa8ac7013470be51075bc05ca1939678fa58608bb562e97fb70206c55b0f9531adea5d34e7de864e679694c841ccc08884c842c0beffaaf113ef298e8b9d8aa476f38a90ba06b457b9b9fdce4759abea7768bc8b800db2d110ceab0de6f5dcfb55be77822c1a7d4a77792d5f32cf1f7bccd0b80c0f9074ca4df666f460ce78be91ccd0a96d7f7cb21e1c52a834828b4a35f69692cd66a1c0ce1a9a7329765b94d608fb672b80f9d0e20c59cb46ab3ae16953aa0905cb9254fb823dbeab341eeb9e03e629c4b4"}
```

**Comment by eliaya** [comment]
@koizu-mkII 
Windows 11 のDOSコマンドを使って"access_token"を正常に取得できたとのことで、ありがとうございました。
```
C:\Users\eliaya>curl -X POST -H "Content-Type:application/json" --data "{\"grant_type\":\"api_key\",\"client_id\":\"78554eb0-48c8-11ef-97d1-4baf83c6f224\",\"client_secret\":\"x0wLCkbltJmvIByFAVmKrX8PcAo6Xo9L6Y7iukRk\",\"api_key\":\"key_N4xExDCzBWtRi4V5ZDJ2ZZIiuhYEcw\",\"scope\":\"me value_write\"}" http://localhost:8082/admin/oauth/token
{"token_type":"Bearer","expires_in":31536000,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI3ODU1NGViMC00OGM4LTExZWYtOTdkMS00YmFmODNjNmYyMjQiLCJqdGkiOiJiNmIzZDE1OTQzOGZmMGQ5MWUxOTQ5OWY3NWIzYjVkY2IyY2M4ZDIzNzQ0OTJhNzc5ZmZiY2IwOGRlN2MwYTQwNjFkN2Q2ZDAwZTdiZDEyMyIsImlhdCI6MTcyMTcyMjIyOC40OTUyNDIsIm5iZiI6MTcyMTcyMjIyOC40OTUyNDQsImV4cCI6MTc1MzI1ODIyOC40NzQzNTIsInN1YiI6IjEiLCJzY29wZXMiOlsibWUiLCJ2YWx1ZV93cml0ZSJdfQ.h9RYBCyfeGk_wKZkQRkOckjmoqomrujRudrSCE2I6sVYXJ7um1EZRSuKO682AYYdK2o6RQRyeTVnhG6_FyorDm4SThj_gSv4yTJdaN-F1pt5fw7vszOO3IhPS5Pbs_LRsuUSbmPKwm54PywLdcMp6Vh-jUGs5FIhYetOkPn1AZjQfdMfviDJ_M0c1k-4UcyujXJus5m_b11OZ5UCXlU_cPf7gLTx7hTA_zyML24uG7Sl3m-q0WpjKUnopt5Crkj-AeYqVEKoVSExjqWriYp2CqCQtlJnjmV_uk4GxW-wtx_u5ut0UKlEBEgWfEGC9O-wIXj270Zr97_cXWCmXastafNbpVnDJ8aU4nMWoNa53N-lI62p1zHaA5vKky0-gFRZZ8A-OnjRfjU73aD63GhNRmXKk4eXchB03iY7fX-1Zzqxb0qbHVCXg30AmW618YhGSoPlopDmnChAVz7_N5HgXASIsDGph-aya4-MRaaCcotf7YR-Hl_Fka704ATU7rkLq8ESdL45HfhErx4VFyI_WRYYmgsAYxeVAR28XcGnGLM5K5F2aqtyHWAAFjPJnVYhzHQlwz1B2g2ijYhNWlA6PYl_ZsXmHjCXvRTnix1O3aoUxeUJvn-fohPO7ywXo0WCdW7qD0SeDZQaJIeNIPUEyeU0la0Oy_-eGbvrv5iWJAU","refresh_token":"def502008c8bd7fe9e8b206c935993acfbb16aea6ad2670fbf5857f37b7061e7f6d0689035372d9dff9749309d8a1208df34e5a65a8270743447448c3eb564385352ae58d31c7cdc869bf09bbff907a5b590d2bf23737e489c12af4e241d1645ee359a92c6869ac667cf2f58abbec5871a628f690cbf5fdf98692f96fc61fa071e78dc5ac20bc2f664a4561ea98eac336c868a581cc17dd2ee29cf7d50e4f91aed30ea1b022cbc256438659e65430948efa3f55a47e4f5eca93a2cb25d22f9d23bc2f684b053fba9a4b12190bc2643c6efaa27b5acf53418a1bf0d60ce3962dbb26761b0fdf5bffbbb580cf092477dde73e6bf323272eae4bbf4d493954b2be4c60bb1aaf230ff7dca2dc6a8ad7c40180151af5c016a71f23d31ebe679bd2154fdd020e484acf9cc01c51d67c4dc3907a1d07d7d1c777bd207e0071b1736635a2c1ced6cf684ee93dca60e64414af43dbb7748b653f1785aeb351a8890f8e2216236e3119d167fbad8ac119bc5c1fdb549dc993e496510bcd8a93f5f01ecbe6fa645f07b94bb329f028614471444afa7f02248d85317"}
```

ただし、Postmanで正しくトークン取得できないようです。
設定のどこかが間違っているのかをあとでもう一度確認してみて、また報告させていただきます。

**Comment by koizu-mkII** [comment]
@eliaya 
Postmanですが、grant_typeなどのパラメータは下図のように　Body　に設定していますか？
![image](https://github.com/user-attachments/assets/25ea7ca2-0318-4040-80a4-c95342f2aa24)

**Comment by eliaya** [comment]
@koizu-mkII 
ヒントのおかげで無事に成功しました。本当にありがとうございました！
![SCR-20240725-bgsu](https://github.com/user-attachments/assets/40cbe5c8-389e-4cf7-9181-1b647896f24e)

APIの使い方を誤解していました。
bugではないようですので、このIssueをcloseさせていただきます。
