### ISSUE TITLE
通知設定で実施アクションがEメールだとエラーになる

### ISSUE THREAD

**Issue by kaziyama00** [exceedone/exment#1507]
### Describe the bug / バグの説明
通知設定でデータ作成時・更新時などに実施アクションがEメールと設定されているときに、データを作成すると"Call to a member function belong_organizations() on null"となる。

### To Reproduce / 再現手順
通知設定で、実施トリガーに"データ新規作成・更新・共有・コメント"、通知条件設定に"作成"、実施アクションに"Eメール"、通知対象に"カスタム列:部門メールアドレス:部門メールアドレス"とし、データを新規に登録するとエラーとなる。
※部門メールアドレス:部門メールアドレスは、別のカスタムテーブル:別のカスタム列の名前です。通知対象のテーブルのカスタム列設定で「選択肢 (他のテーブルの値一覧から選択)」としている項目から取得しています。

### Version / 発生バージョン
6.1.2で発生した
6.1.1では発生していなかった

### Error log / エラーログ

[2024-09-09 11:21:29] local.ERROR: Call to a member function belong_organizations() on null {"userId":6,"exception":"[object] (Error(code: 0): Call to a member function belong_organizations() on null at /hogehoge/laravel/exment/vendor/exceedone/exment/src/Model/LoginUser.php:124)
[stacktrace]
#0 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(804): Exceedone\\Exment\\Model\\LoginUser->belong_organizations()
#1 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(110): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#2 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(802): Illuminate\\Database\\Eloquent\\Relations\\Relation::noConstraints(Object(Closure))
#3 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(776): Illuminate\\Database\\Eloquent\\Builder->getRelation('belong_organiza...')
#4 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(756): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'belong_organiza...', Object(Closure))
#5 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(705): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#6 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(109): Illuminate\\Database\\Eloquent\\Model->load(Array)
#7 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(62): Exceedone\\Exment\\Jobs\\MailSendJob->restoreModel(Object(Illuminate\\Contracts\\Database\\ModelIdentifier))
#8 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(93): Exceedone\\Exment\\Jobs\\MailSendJob->getRestoredPropertyValue(Object(Illuminate\\Contracts\\Database\\ModelIdentifier))
#9 [internal function]: Exceedone\\Exment\\Jobs\\MailSendJob->__unserialize(Array)
#10 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(97): unserialize('O:48:\"Illuminat...')
#11 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(246): Illuminate\\Queue\\CallQueuedHandler->getCommand(Array)
#12 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(236): Illuminate\\Queue\\CallQueuedHandler->failed(Array, Object(Error), '30b9c35b-063c-4...')
#13 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(215): Illuminate\\Queue\\Jobs\\Job->failed(Object(Error))
#14 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(118): Illuminate\\Queue\\Jobs\\Job->fail(Object(Error))
#15 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(47): Illuminate\\Queue\\SyncQueue->handleException(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(Error))
#16 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(254): Illuminate\\Queue\\SyncQueue->push(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#17 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(230): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(Illuminate\\Notifications\\SendQueuedNotifications))
#18 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#19 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(229): Illuminate\\Bus\\Dispatcher->dispatch(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#20 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(76): Illuminate\\Notifications\\NotificationSender->queueNotification(Array, Object(Exceedone\\Exment\\Jobs\\MailSendJob))
#21 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send(Array, Object(Exceedone\\Exment\\Jobs\\MailSendJob))
#22 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send(Object(Exceedone\\Exment\\Notifications\\MailSender), Object(Exceedone\\Exment\\Jobs\\MailSendJob))
#23 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Notifications/MailSender.php(247): Exceedone\\Exment\\Notifications\\MailSender->notify(Object(Exceedone\\Exment\\Jobs\\MailSendJob))
#24 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Notifications/MailSender.php(218): Exceedone\\Exment\\Notifications\\MailSender->sendMail()
#25 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Services/NotifyService.php(487): Exceedone\\Exment\\Notifications\\MailSender->send()
#26 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Services/NotifyService.php(413): Exceedone\\Exment\\Services\\NotifyService::notifyMail(Array)
#27 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Model/Notify.php(358): Exceedone\\Exment\\Services\\NotifyService::executeNotifyAction(Object(Exceedone\\Exment\\Model\\Notify), Array)
#28 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Model/Notify.php(265): Exceedone\\Exment\\Model\\Notify->notifyUser(Object(Exceedone\\Exment\\Model\\Class_64d6b2253863319df8b0), Array)
#29 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Model/CustomValue.php(833): Exceedone\\Exment\\Model\\Notify->notifyCreateUpdateUser(Object(Exceedone\\Exment\\Model\\Class_64d6b2253863319df8b0), Object(Exceedone\\Exment\\Enums\\NotifySavedType))
#30 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Model/CustomValue.php(593): Exceedone\\Exment\\Model\\CustomValue->notify('created')
#31 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Model/CustomValue.php(487): Exceedone\\Exment\\Model\\CustomValue->savedEvent(true)
#32 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(458): Exceedone\\Exment\\Model\\CustomValue::Exceedone\\Exment\\Model\\{closure}(Object(Exceedone\\Exment\\Model\\Class_64d6b2253863319df8b0))
#33 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('eloquent.create...', Array)
#34 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners('eloquent.create...', Array, false)
#35 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(215): Illuminate\\Events\\Dispatcher->dispatch('eloquent.create...', Array)
#36 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1320): Illuminate\\Database\\Eloquent\\Model->fireModelEvent('created', false)
#37 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1138): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Exceedone\\Exment\\Database\\Eloquent\\ExtendedBuilder))
#38 /hogehoge/laravel/exment/vendor/exceedone/laravel-admin/src/Form.php(464): Illuminate\\Database\\Eloquent\\Model->save()
#39 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Database/ConnectionTrait.php(92): Encore\\Admin\\Form->Encore\\Admin\\{closure}(Object(Exceedone\\Exment\\Database\\MariaDBConnection))
#40 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(509): Exceedone\\Exment\\Database\\MariaDBConnection->transaction(Object(Closure))
#41 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Database\\DatabaseManager->__call('transaction', Array)
#42 /hogehoge/laravel/exment/vendor/exceedone/laravel-admin/src/Form.php(457): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)
#43 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Controllers/HasResourceTableActions.php(34): Encore\\Admin\\Form->store()
#44 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Controllers/CustomValueController.php(106): Exceedone\\Exment\\Controllers\\CustomValueController->storeTrait()
#45 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Controllers/AdminControllerTableBase.php(59): Exceedone\\Exment\\Controllers\\CustomValueController->store('innder_snd_rcv_...')
#46 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Exceedone\\Exment\\Controllers\\AdminControllerTableBase->callAction('store', Array)
#47 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Exceedone\\Exment\\Controllers\\CustomValueController), 'store')
#48 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#49 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#50 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /hogehoge/laravel/exment/vendor/exceedone/laravel-admin/src/Middleware/Session.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Encore\\Admin\\Middleware\\Session->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /hogehoge/laravel/exment/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Encore\\Admin\\Middleware\\Permission->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /hogehoge/laravel/exment/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Encore\\Admin\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\LogOperation->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /hogehoge/laravel/exment/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Encore\\Admin\\Middleware\\Pjax->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/Bootstrap.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Morph->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\AuthenticatePasswordLimit->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Authenticate2factor->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/Authenticate.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/Initialize.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Initialize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\\Exment\\Middleware\\IpFilterBase->handleBase(Object(Illuminate\\Http\\Request), Object(Closure), 'web_ip_filters')
#75 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\WebIPFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/Browser.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Browser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#86 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#93 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#94 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#95 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#96 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#97 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#98 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/ExmentDebug.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\ExmentDebug->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#100 /hogehoge/laravel/exment/vendor/exceedone/exment/src/Middleware/TrustProxies.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#101 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#102 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#103 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#104 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#105 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#106 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#107 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#108 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#109 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#110 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#111 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#112 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#113 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#114 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#115 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#116 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#117 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#118 /hogehoge/laravel/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#119 /hogehoge/laravel/exment/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#120 {main}
"}

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
通知設定の「有効フラグ」をNOにしてExmentへのデータ登録時のエラーを回避していますが、通知機能を使用して他のシステムに内容と添付ファイルを送信して連携しているので、他システムへのデータ登録が出来ていません。

**Comment by f-takahiro-watanabe** [comment]
当方の環境でも発生しております。
発生するテーブルと発生しないテーブルが存在するため、切り分けを行いました。

当方の環境ではフォーム優先順位設定で「ログインユーザーの所属組織」を設定している場合のみ発生しております。

実施アクションに"Eメール"、通知対象を"作成者"としております。
実施アクションに"Eメール"、通知対象を"カスタム列:ユーザーXX"も試しましたが上記の優先順位設定がなければエラーになりませんでした。
※カスタム列:ユーザーXX→システムテーブルのユーザーです。
※起票者様の「選択肢 (他のテーブルの値一覧から選択)」したカスタム列を通知先に選択する方法がわかりませんでした。


起票者様と条件が異なる可能性がありますが、参考までにコメントさせていただきました。
<img width="791" alt="image" src="https://github.com/user-attachments/assets/8bc39043-b92a-4d59-94e9-079517303ad4">

**Comment by kaziyama00** [comment]
切り分けありがとうございます。
こちらもフォーム優先順位設定で「ログインユーザーの所属組織」を設定しております。
先ほど、「ログインユーザーの所属組織」を設定しているフォームに対して、条件を外してデータ登録・通知メールを行ったところ正常に通知されました。
ありがとうございます。

エラーがbelong_organizations()を呼び出した時なので組織関連のものとは思っていましたが、フォームの優先順位の方とは思いませんでした。
発生条件としては、v6.1.2でフォーム優先順位設定で「ログインユーザーの所属組織」を設定して、通知の実行アクションに"Eメール"を指定している時、となりますね。
将来バージョンで修正していただければと思います。

**Comment by kaziyama00** [comment]
「選択肢 (他のテーブルの値一覧から選択)」したカスタム列を通知先に選択する方法、ですが、別テーブルにしてある部門ごとのメールアドレスを、「選択肢 (他のテーブルの値一覧から選択)」としてカスタム列に追加しておくと、「通知」の[通知アクション]-[通知対象]に出てきませんか?

![image](https://github.com/user-attachments/assets/2c628a1a-ea86-417a-8932-dd4c1578b679)

**Comment by f-takahiro-watanabe** [comment]
@kaziyama00 

試してみたところ表示されました！
ご教授ありがとうございます。

また、外部連携でメール通知を利用されていることを拝見して目から鱗が落ちました。
外部のWebAPIを実行するプラグインを作成しようと考えていたところでしたので、
もっと簡易的に実装する際の参考にさせていただきます。
（弊社はMicrosoft365環境のため、PowerAutomateで色々と活用の幅が広がりそうです）

スレッドの内容と関係のないコメントになってしまいましたので、以上とさせていただきます。

**test20240909-6**
![image](https://github.com/user-attachments/assets/913a67e7-21f0-4f95-9d1f-20e65102c3d8)

**test20240909-5**
![image](https://github.com/user-attachments/assets/c91cfb40-4202-4bd4-b3f0-82e9d7230e3c)

**Comment by kaziyama00** [comment]
@f-takahiro-watanabe
こちらもMicrosoft365環境でまさにPowerAutomateでメールの内容と添付ファイルをPlannerに登録するということをやっております。
今回の件で、通知だけでもTeamsにWebhookで行おうとしましたが、今後Incoming Webhookはなくなることがわかっているし
Workflow(=PowerAutomate)のWebhookはアダプティブカード形式なので、Exmentから添付ファイルを送れるかどうかまでは追えていませんでしたので、f-takahiro-watanabeさんのコメントで助かりました。
こちらも以上とさせていただきます。
