### ISSUE TITLE
ページあたり行数を変更すると特定の条件でエラー

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1543]
### Describe the bug / バグの説明
ページあたり行数を変更すると特定の条件でエラーになります。

### To Reproduce / 再現手順
例えば以下の条件で発生。

1. テーブルの行数は100行
2. ページあたり行数は50行
3. 2ページ目に遷移（50行が表示される）
4. ページ当たり行数を100行に変更
5. エラー発生

2ページ目以降で、ページ当たり行数を、表示対象の行数より大きくすると発生するようです。
1ページ目では起こりません。

全プラグイン無効化し、列が1つしかなくビューもフォームもデフォルトなカスタムテーブルでも再現しました。

### Version / 発生バージョン
v6.1.8

### Error log / エラーログ
```
[2024-12-06 14:14:36] local.ERROR: Encore\Admin\Middleware\Pjax::respond(): Argument #1 ($response) must be of type Illuminate\Http\Response, Illuminate\Http\RedirectResponse given, called in /var/www/exment-test/vendor/exceedone/laravel-admin/src/Grid/Model.php on line 521 {"userId":143,"exception":"[object] (TypeError(code: 0): Encore\\Admin\\Middleware\\Pjax::respond(): Argument #1 ($response) must be of type Illuminate\\Http\\Response, Illuminate\\Http\\RedirectResponse given, called in /var/www/exment-test/vendor/exceedone/laravel-admin/src/Grid/Model.php on line 521 at /var/www/exment-test/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php:51)
[stacktrace]
#0 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Grid/Model.php(521): Encore\\Admin\\Middleware\\Pjax::respond()
#1 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Grid/Model.php(469): Encore\\Admin\\Grid\\Model->handleInvalidPage()
#2 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Grid/Model.php(364): Encore\\Admin\\Grid\\Model->get()
#3 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Grid/Filter.php(555): Encore\\Admin\\Grid\\Model->buildData()
#4 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Grid/Concerns/HasFilter.php(65): Encore\\Admin\\Grid\\Filter->execute()
#5 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Grid.php(655): Encore\\Admin\\Grid->applyFilter()
#6 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Grid.php(1103): Encore\\Admin\\Grid->build()
#7 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Layout/Column.php(95): Encore\\Admin\\Grid->render()
#8 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Layout/Row.php(124): Encore\\Admin\\Layout\\Column->build()
#9 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Layout/Content.php(224): Encore\\Admin\\Layout\\Row->build()
#10 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Layout/Content.php(306): Encore\\Admin\\Layout\\Content->build()
#11 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Encore\\Admin\\Layout\\Content->render()
#12 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#13 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(918): Illuminate\\Http\\Response->__construct()
#14 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\\Routing\\Router::toResponse()
#15 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Routing\\Router->prepareResponse()
#16 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#17 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Middleware/Session.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Encore\\Admin\\Middleware\\Session->handle()
#19 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Encore\\Admin\\Middleware\\Permission->handle()
#21 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Encore\\Admin\\Middleware\\Bootstrap->handle()
#23 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\LogOperation->handle()
#25 /var/www/exment-test/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Encore\\Admin\\Middleware\\Pjax->handle()
#27 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/Bootstrap.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Bootstrap->handle()
#29 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Morph->handle()
#31 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\AuthenticatePasswordLimit->handle()
#33 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Authenticate2factor->handle()
#35 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/Authenticate.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Authenticate->handle()
#37 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/Initialize.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Initialize->handle()
#39 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\\Exment\\Middleware\\IpFilterBase->handleBase()
#41 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\WebIPFilter->handle()
#42 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/Browser.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\Browser->handle()
#44 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#46 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#48 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#50 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#52 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#53 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#55 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#57 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#59 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#60 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#61 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#62 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#63 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#64 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/ExmentDebug.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\ExmentDebug->handle()
#66 /var/www/exment-test/vendor/exceedone/exment/src/Middleware/TrustProxies.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Exceedone\\Exment\\Middleware\\TrustProxies->handle()
#68 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#70 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#71 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#73 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#74 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#76 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#78 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#80 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#82 /var/www/exment-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#83 /var/www/exment-test/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle()
#84 {main}
"}

```

**Comment by KajitoriAdmin** [comment]
@a-nagai-dkg 
v6.2.1 にて対応しました。

**Comment by a-nagai-dkg** [comment]
ご対応ありがとうございます！
アップデートし、不具合が再現しないことを確認いたしました！

今後とも何とぞよろしくお願いいたします。
