### ISSUE TITLE
メニューに追加ページを追加した時にエラーが出る

### ISSUE THREAD

**Issue by ebiyuu1121** [exceedone/exment#436]
**Describe the bug / バグの説明**
メニューに行追加ページ（/create）を追加した時に、一般ユーザーだとエラーが出る。

**To Reproduce / 再現手順**
1. メニューにカスタムURL形式で `/admin/data/{table_name}/create` を追加する。
2. 全テーブル編集権限を持たないユーザーのアカウントでログインする。

**Error log / エラーログ**

```
[2019-10-12 13:38:40] local.ERROR:  (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) {"userId":3,"exception":"[object] (ErrorException(code: 0):  (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) at /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:939, ErrorException(code: 0):  (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) at /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:939, ErrorException(code: 0):  (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) at /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:939, ErrorException(code: 0):  (View: /Users/ebiyuu1121/projects/exment/resources/views/vendor/admin/partials/menu.blade.php) at /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:939, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0):  at /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:939)
[stacktrace]
#0 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/Users/ebiyuu11...', Array)
#2 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\\View\\Engines\\CompilerEngine->get('/Users/ebiyuu11...', Array)
#3 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\\View\\View->getContents()
#4 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\\View\\View->renderContents()
#5 /Users/ebiyuu1121/projects/exment/vendor/exceedone/laravel-admin/src/Layout/Content.php(308): Illuminate\\View\\View->render()
#6 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Encore\\Admin\\Layout\\Content->render()
#7 /Users/ebiyuu1121/projects/exment/vendor/symfony/http-foundation/Response.php(202): Illuminate\\Http\\Response->setContent(Object(Encore\\Admin\\Layout\\Content))
#8 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(733): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Encore\\Admin\\Layout\\Content))
#9 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Encore\\Admin\\Layout\\Content))
#10 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Encore\\Admin\\Layout\\Content))
#11 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/ebiyuu1121/projects/exment/vendor/exceedone/laravel-admin/src/Middleware/Session.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\\Admin\\Middleware\\Session->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/ebiyuu1121/projects/exment/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(42): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\\Admin\\Middleware\\Permission->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/ebiyuu1121/projects/exment/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\\Admin\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/ebiyuu1121/projects/exment/vendor/exceedone/laravel-admin/src/Middleware/LogOperation.php(38): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\\Admin\\Middleware\\LogOperation->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/ebiyuu1121/projects/exment/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\\Admin\\Middleware\\Pjax->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/ebiyuu1121/projects/exment/vendor/exceedone/exment/src/Middleware/Bootstrap.php(23): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/ebiyuu1121/projects/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Morph->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/ebiyuu1121/projects/exment/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(23): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\AuthenticatePasswordLimit->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/ebiyuu1121/projects/exment/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(23): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Authenticate2factor->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/ebiyuu1121/projects/exment/vendor/exceedone/exment/src/Middleware/Authenticate.php(39): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/ebiyuu1121/projects/exment/vendor/exceedone/exment/src/Middleware/Initialize.php(55): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Initialize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#65 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#66 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#67 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#68 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#69 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/ebiyuu1121/projects/exment/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#87 /Users/ebiyuu1121/projects/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#88 /Users/ebiyuu1121/projects/exment/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#89 {main}
"} 
```

**Comment by hirossyi73** [comment]
@ebiyuu1121 
v2.1.8にて対応いたしました。ご確認をお願いいたします。

**Comment by ebiyuu1121** [comment]
素早い対応ありがとうございます
アップデートスクリプトに難航しておりすぐの確認はできませんが、確認させていただきます

**Comment by ebiyuu1121** [comment]
@hirossyi73 修正を確認しました
ありがとうございます。
