### ISSUE TITLE
通知されたことのあるカスタムテーブルを削除すると「通知一覧」表示でエラーになる

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#667]
**Describe the bug / バグの説明**
通知（システム内アラート）されたことのあるカスタムテーブルを削除してから「通知一覧」を表示するとエラーになります。

削除されたカスタムテーブルに紐づく通知が残っていることが原因のようです。同名のカスタムテーブルを再作成してそれに対応する通知をすべて削除することで、カスタムテーブルを削除したあともエラーが発生しなくなりました。

**Version / 発生バージョン**
v3.3.0

**Error log / エラーログ**
```
[2020-06-17 10:18:00] local.ERROR: ErrorException: Trying to get property 'table_view_name' of non-object in /var/www/exment/vendor/exceedone/exment/src/Controllers/NotifyNavbarController.php:38
Stack trace:
#0 /var/www/exment/vendor/exceedone/exment/src/Controllers/NotifyNavbarController.php(38): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/exment...', 38, Array)
#1 [internal function]: Exceedone\Exment\Controllers\NotifyNavbarController->Exceedone\Exment\Controllers\{closure}('table_x', Object(Encore\Admin\Grid\Column), Object(Exceedone\Exment\Model\NotifyNavbar))
#2 /var/www/exment/vendor/exceedone/laravel-admin/src/Grid/Column.php(747): call_user_func_array(Object(Closure), Array)
#3 /var/www/exment/vendor/exceedone/laravel-admin/src/Grid/Column.php(810): Encore\Admin\Grid\Column->callDisplayEscapeCallbacks('table_x', 0)
#4 /var/www/exment/vendor/exceedone/laravel-admin/src/Grid.php(614): Encore\Admin\Grid\Column->fill(Array)
#5 [internal function]: Encore\Admin\Grid->Encore\Admin\{closure}(Object(Encore\Admin\Grid\Column), 2)
#6 /var/www/exment/vendor/laravel/framework/src/Illuminate/Support/Collection.php(932): array_map(Object(Closure), Array, Array)
#7 /var/www/exment/vendor/exceedone/laravel-admin/src/Grid.php(617): Illuminate\Support\Collection->map(Object(Closure))
#8 /var/www/exment/vendor/exceedone/laravel-admin/src/Grid.php(1020): Encore\Admin\Grid->build()
#9 /var/www/exment/vendor/exceedone/laravel-admin/src/Layout/Column.php(93): Encore\Admin\Grid->render()
#10 /var/www/exment/vendor/exceedone/laravel-admin/src/Layout/Row.php(80): Encore\Admin\Layout\Column->build()
#11 /var/www/exment/vendor/exceedone/laravel-admin/src/Layout/Content.php(223): Encore\Admin\Layout\Row->build()
#12 /var/www/exment/vendor/exceedone/laravel-admin/src/Layout/Content.php(305): Encore\Admin\Layout\Content->build()
#13 /var/www/exment/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Encore\Admin\Layout\Content->render()
#14 /var/www/exment/vendor/symfony/http-foundation/Response.php(205): Illuminate\Http\Response->setContent(Object(Encore\Admin\Layout\Content))
#15 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(733): Symfony\Component\HttpFoundation\Response->__construct(Object(Encore\Admin\Layout\Content))
#16 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Encore\Admin\Layout\Content))
#17 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Encore\Admin\Layout\Content))
#18 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Session.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\Admin\Middleware\Session->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\Admin\Middleware\Permission->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\Admin\Middleware\Bootstrap->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\LogOperation->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\Admin\Middleware\Pjax->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/exment/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/exment/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/exment/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/exment/vendor/exceedone/exment/src/Middleware/Bootstrap.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Bootstrap->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Morph->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/exment/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\AuthenticatePasswordLimit->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(23): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Authenticate2factor->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate.php(39): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/exment/vendor/exceedone/exment/src/Middleware/Initialize.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Initialize->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\Exment\Middleware\IpFilterBase->handleBase(Object(Illuminate\Http\Request), Object(Closure), 'web_ip_filters')
#63 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\WebIPFilter->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/exment/vendor/exceedone/exment/src/Middleware/Browser.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Browser->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /var/www/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /var/www/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#78 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#81 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#83 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#84 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#86 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#87 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#88 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#89 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#90 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#91 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#92 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#93 /var/www/exment/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#94 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#95 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#96 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#97 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#98 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#99 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#100 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#101 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#103 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#104 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#105 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#106 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#107 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#108 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#109 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#110 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#111 /var/www/exment/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#112 {main}  
```

**Screenshots / スクリーンショット**
![screen](https://user-images.githubusercontent.com/66708775/84845746-44879b00-b088-11ea-9063-e29f03da4a96.png)

**Comment by hirossyi73** [comment]
v3.3.1で対応しました。
