### ISSUE TITLE
入力項目「選択肢（他のテーブルの値一覧から選択）」に選択肢があらわれないことがある

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#773]
**Describe the bug / バグの説明**
データの新規追加や編集で入力項目「選択肢（他のテーブルの値一覧から選択）」に選択肢があらわれないことがあります。カスタム列に「関連絞り込み」と「絞り込み条件ビュー」を設定すると選択肢があらわれなくなるようです。

関連絞り込みで設定した列（親テーブルにあたる列）に何か入力すると、ログファイルにエラーメッセージが出力されます。

**Version / 発生バージョン**
 v3.6.4

**Error log / エラーログ**
```text
[2020-09-15 11:20:11] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'column_9fa0e1faf5d751253335' in 'order clause' (SQL: select `id` from ((select `id` from `exm__47acb84ff27f17cf55ac` where (((`column_9fa0e1faf5d751253335` LIKE [%] and JSON_SEARCH(column_9fa0e1faf5d751253335, 'one', '1') is not null) or `column_9fa0e1faf5d751253335` = 1)) and `exm__47acb84ff27f17cf55ac`.`deleted_at` is null limit 5000) union (select `id` from `exm__47acb84ff27f17cf55ac` where `column_d8a8362a2f987874f538` is null and (((`column_9fa0e1faf5d751253335` LIKE [%] and JSON_SEARCH(column_9fa0e1faf5d751253335, 'one', '1') is not null) or `column_9fa0e1faf5d751253335` = 1)) and `exm__47acb84ff27f17cf55ac`.`deleted_at` is null limit 5000)) as `sub` order by CAST(column_9fa0e1faf5d751253335 AS signed) asc, CAST(column_d8a8362a2f987874f538 AS signed) asc, column_3137549efa4652df03d8 asc) {"userId":1,"email":"admin@trial.local","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'column_9fa0e1faf5d751253335' in 'order clause' (SQL: select `id` from ((select `id` from `exm__47acb84ff27f17cf55ac` where (((`column_9fa0e1faf5d751253335` LIKE [%] and JSON_SEARCH(column_9fa0e1faf5d751253335, 'one', '1') is not null) or `column_9fa0e1faf5d751253335` = 1)) and `exm__47acb84ff27f17cf55ac`.`deleted_at` is null limit 5000) union (select `id` from `exm__47acb84ff27f17cf55ac` where `column_d8a8362a2f987874f538` is null and (((`column_9fa0e1faf5d751253335` LIKE [%] and JSON_SEARCH(column_9fa0e1faf5d751253335, 'one', '1') is not null) or `column_9fa0e1faf5d751253335` = 1)) and `exm__47acb84ff27f17cf55ac`.`deleted_at` is null limit 5000)) as `sub` order by CAST(column_9fa0e1faf5d751253335 AS signed) asc, CAST(column_d8a8362a2f987874f538 AS signed) asc, column_3137549efa4652df03d8 asc) at /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'column_9fa0e1faf5d751253335' in 'order clause' at /var/www/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'column_9fa0e1faf5d751253335' in 'order clause' at /var/www/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)
[stacktrace]
#0 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `id` fro...', Array, Object(Closure))
#1 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select `id` fro...', Array, Object(Closure))
#2 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1963): Illuminate\\Database\\Connection->select('select `id` fro...', Array, true)
#3 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1951): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2435): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1952): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /var/www/exment/vendor/exceedone/exment/src/Model/CustomTable.php(1237): Illuminate\\Database\\Query\\Builder->get()
#7 /var/www/exment/vendor/exceedone/exment/src/Model/CustomTable.php(1299): Exceedone\\Exment\\Model\\CustomTable->searchValue(NULL, Array)
#8 /var/www/exment/vendor/exceedone/exment/src/Controllers/ApiDataController.php(705): Exceedone\\Exment\\Model\\CustomTable->searchRelationValue('3', NULL, Object(Exceedone\\Exment\\Model\\CustomTable), Array)
#9 [internal function]: Exceedone\\Exment\\Controllers\\ApiDataController->relatedLinkage(Object(Illuminate\\Http\\Request), 'child')
#10 /var/www/exment/vendor/exceedone/exment/src/Controllers/ApiDataController.php(47): call_user_func_array(Array, Array)
#11 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Exceedone\\Exment\\Controllers\\ApiDataController->callAction('relatedLinkage', Array)
#12 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Exceedone\\Exment\\Controllers\\ApiDataController), 'relatedLinkage')
#13 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#14 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#15 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\LogOperation->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Morph->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/exment/vendor/exceedone/exment/src/Middleware/AuthenticateApi.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\AuthenticateApi->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\\Exment\\Middleware\\IpFilterBase->handleBase(Object(Illuminate\\Http\\Request), Object(Closure), 'web_ip_filters')
#27 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\WebIPFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#49 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#50 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#51 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#52 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#53 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/exment/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#71 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#72 /var/www/exment/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#73 {main}
"}
```

**Comment by hirossyi73** [comment]
@shimaday8 
以下の情報を追加でいただけないでしょうか。

・「関連絞り込み」で、関連付け設定をしている方法は、リレーション、もしくは「選択肢（他のテーブルの値一覧から選択）」
例：
「顧客」を選択時に「契約」が絞り込まれている関連付けの時に、顧客と契約は、1:nリレーション、n:nリレーション、契約テーブルに、列種類「選択肢（他のテーブルの値一覧から選択）」のいずれが含まれているかどうか

・上記の例で「契約」テーブルに、データが何件ほど含まれているか（100件以上となっているか）

**Comment by shimaday8** [comment]
関係するテーブルは「親＞子＞孫」という親子関係を持ち、すべて「選択肢（他のテーブルの値一覧から選択）」で関連付けています。データ件数は、親は3件、子は9件です。孫の入力画面で親を選択しても子の選択肢があらわれません。

ご回答を受け、追加調査のためにカスタムテーブルを一から作成してみたところ、現象が再現しませんでした。過去のバージョンから存在しているカスタムテーブルで発生しています。どのバージョンから存在していたカスタムテーブルかはわかりません。カスタムテーブルやカスタム列の設定はいろいろと変更しており、作成当初のままではありません。

また、「サーチ」ボタンを押して別画面に表示される一覧画面には正しく選択肢があらわれました。

現象が発生しているカスタムテーブルをテンプレートに出力して、まっさらなv3.6.4環境にインポートしたところ、現象が再現しました。ご報告している以外にも何か設定の不備が潜んでいるのかもしれません。出力したテンプレートを添付いたします。ご参考になれば幸いです。
[template.zip](https://github.com/exceedone/exment/files/5231107/template.zip)

**Comment by hirossyi73** [comment]
テンプレート、ありがとうございます。
調査していたところ、「絞り込み条件ビュー」で指定しているビューで、「並べ替え設定」を行っていると、この現象が発生することが分かりました。

ただ、この修正が、少々影響範囲の大きいものになっておりまして、修正、検証にお時間かかりそうです。
もし業務などに影響がありましたら、直近では、該当のビューの「並べ替え設定」を削除いただけると、一時的な回避は可能です。

**Comment by shimaday8** [comment]
原因および回避方法のご提示ありがとうございます。
検討させていただきます。

**Comment by hirossyi73** [comment]
v3.6.5にて、並べ替え設定を行っていても表示されるようリリースしましたので、ご確認ください。

**Comment by shimaday8** [comment]
修正されていることを確認しました。
ありがとうございました。
