### ISSUE TITLE
自己参照しているカスタムテーブルの関連データ検索でエラーログが出力される

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#787]
**Describe the bug / バグの説明**
自己参照しているカスタムテーブルの関連データ検索でエラーログが出力されます。

本件、たまたま気がついたのでご報告させていただきました。システムを利用する上ではさほど困っていません。

**Version / 発生バージョン**
v3.6.5

**Error log / エラーログ**
```text
[2020-09-25 18:28:22] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select count(*) as aggregate from `exm__67a38cfa2eb00a524c64` inner join (select `id` from `exm__67a38cfa2eb00a524c64` where `` is null and `exm__67a38cfa2eb00a524c64`.`deleted_at` is null) as `sub` on `sub`.`id` = `exm__67a38cfa2eb00a524c64`.`id` where `exm__67a38cfa2eb00a524c64`.`deleted_at` is null) {"userId":1,"email":"admin@trial.local","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select count(*) as aggregate from `exm__67a38cfa2eb00a524c64` inner join (select `id` from `exm__67a38cfa2eb00a524c64` where `` is null and `exm__67a38cfa2eb00a524c64`.`deleted_at` is null) as `sub` on `sub`.`id` = `exm__67a38cfa2eb00a524c64`.`id` where `exm__67a38cfa2eb00a524c64`.`deleted_at` is null) at /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' at /var/www/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' at /var/www/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)
[stacktrace]
#0 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select count(*)...', Array, Object(Closure))
#2 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1963): Illuminate\\Database\\Connection->select('select count(*)...', Array, true)
#3 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1951): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2435): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1952): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2048): Illuminate\\Database\\Query\\Builder->get()
#7 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2021): Illuminate\\Database\\Query\\Builder->runPaginationCountQuery(Array)
#8 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(710): Illuminate\\Database\\Query\\Builder->getCountForPagination()
#9 /var/www/exment/vendor/exceedone/exment/src/Model/CustomTable.php(1202): Illuminate\\Database\\Eloquent\\Builder->paginate(5)
#10 /var/www/exment/vendor/exceedone/exment/src/Model/CustomTable.php(1305): Exceedone\\Exment\\Model\\CustomTable->searchValue('1', Array)
#11 /var/www/exment/vendor/exceedone/exment/src/Controllers/SearchController.php(294): Exceedone\\Exment\\Model\\CustomTable->searchRelationValue('3', '1', Object(Exceedone\\Exment\\Model\\CustomTable), Array)
#12 [internal function]: Exceedone\\Exment\\Controllers\\SearchController->getRelationList(Object(Illuminate\\Http\\Request))
#13 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#14 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('getRelationList', Array)
#15 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Exceedone\\Exment\\Controllers\\SearchController), 'getRelationList')
#16 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#17 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#18 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Session.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\\Admin\\Middleware\\Session->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(42): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\\Admin\\Middleware\\Permission->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\\Admin\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\LogOperation->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\\Admin\\Middleware\\Pjax->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/exment/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/exment/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/exment/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/exment/vendor/exceedone/exment/src/Middleware/Bootstrap.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Morph->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/exment/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\AuthenticatePasswordLimit->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(23): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Authenticate2factor->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate.php(39): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/exment/vendor/exceedone/exment/src/Middleware/Initialize.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Initialize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\\Exment\\Middleware\\IpFilterBase->handleBase(Object(Illuminate\\Http\\Request), Object(Closure), 'web_ip_filters')
#63 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\WebIPFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /var/www/exment/vendor/exceedone/exment/src/Middleware/Browser.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Browser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#72 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /var/www/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#75 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /var/www/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#78 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#81 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#84 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#87 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#88 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#89 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#90 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#91 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#92 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#93 /var/www/exment/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#94 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#96 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#97 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#98 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#100 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#101 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#102 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#103 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#104 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#105 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#106 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#107 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#108 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#109 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#110 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#111 /var/www/exment/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#112 {main}
"}
```

**Screenshots / スクリーンショット**
![search](https://user-images.githubusercontent.com/66708775/94252575-148d4500-ff5f-11ea-9f20-1ad3405440d2.png)

**Comment by dev-hayash** [comment]
横からすみません。
本現象に私も遭遇したので調べていました。
v3.7.2での結果です。

現象が発生する条件は、起票の図で言うと`関連するテーブル`のカラム属性に`検索インデックス`が指定されている場合のようです。

しかし、`検索インデックス`を指定しないと関連データとしてみなしてもらえないような動作でもあります。

**Comment by dev-hayash** [comment]
同じ現象にまたはまってしまったので、忘れないうちに備忘録を追記します。

[テーブル]
　├　カラムA　ID
　└　カラムB　IDを自己参照するカラム　<-ここに検索インデックスを指定すると例外が起きる。

【サンプルデータ】
[資産台帳テーブル]
　ID：CABINET1　資産名：キャビネット１　保存先資産：（null）
　ID：NOTE_PC1　資産名：ノートPC１　保存先資産：CABINET1

検索インデックスを指定した理由は、CABINET1を関連データで、以下のような表示にしたかったが
検索インデックスを保存先資産カラムに指定しないと、★のブロックが関連データに表示されないため。

[資産台帳テーブル]
　ID：CABINET1　資産名：キャビネット１　保存先資産：（null）
[資産台帳テーブル★]
　ID：NOTE_PC1　資産名：ノートPC１　保存先資産：CABINET1

**Comment by hirossyi73** [comment]
@dev-hayash 
こちらでも試してみたのですが、開発者ならびに私の両方とも、再現しない状況です。
ご記載いただいた

```
[テーブル]
　├　カラムA　ID
　└　カラムB　IDを自己参照するカラム　<-ここに検索インデックスを指定すると例外が起きる。
```
以外に、なにか関係ありそうな設定は行っていますでしょうか？

**Comment by dev-hayash** [comment]
ご確認ありがとうございます。

大変申し訳ありませんが、デモサイトに現象再現テーブルデータを作成させて頂きました。

https://demo-jp.exment.net/admin/data/asset_table

こちらの資産台帳テーブルのID1（MNT-202004-111）の関連データ検索を行うと、再現する事を確認できました。

**Comment by hirossyi73** [comment]
ありがとうございます。

デモ環境のデータをリストアし、ローカル環境で実施した所、正常に検索できました。
何らかの環境差異で実施可否が異なると思いますので、もう少し調査します。
