### ISSUE TITLE
親子リレーションの子テーブルにユニークカラムがあるとレコード更新で重複エラーになる

### ISSUE THREAD

**Issue by dev-hayash** [exceedone/exment#792]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

親子リレーションの子テーブルにユニークカラムがあるとレコード更新で重複エラーになる。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

【１．テーブル作成】
［親テーブル］
カラム１：1行テキスト

［子テーブル］
カラム１：1行テキスト　必須、ユニークを指定

【２．リレーション設定】
・親テーブル側のリレーション設定で、子テーブルを1対多で指定する。

【３．フォーム登録】
・親テーブルのカスタムフォームで、子テーブルを使用するにチェックする。
・子テーブルのカラム１のフォーム項目はデフォルト（表示専用、隠しフィールド、必須　チェック無し、データ連動無し）

【４．レコード追加】
・親テーブルのデータ一覧から新規レコード追加。親と子の入力フォームが表示される。
・フォーム画面で親のカラム１を入力し、子のレコードを追加。子のカラム１を入力する。
・保存を押し、親と子のレコードが保存される。

【５．レコード修正】
・親テーブルのデータ一覧画面にて、４で保存したレコードの編集をクリックする。
・そのまま保存を押すと、子テーブルのカラム１が「すでに使われています」とエラーになる。

![image](https://user-images.githubusercontent.com/19341340/94634751-d3ed4d00-030b-11eb-9f79-8bc083eb1e82.png)

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.6.1

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

関係のない別なエラーだと思いますが最後のエラーを抜粋します。

[2020-09-30 09:27:53] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'order clause' (SQL: select `id` from ((select `id` from `exm__5ce761f4dfcbf63010e9` where 0 = 1 and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_c47ed046ac8504d59a44` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_2137450de3bf41f9f06d` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_fb5fa64105453e89b3a0` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_7aac560f5062dd08e6d4` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_0cd0a0c5b21930e5e26b` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_7ba5838c9db1d8d5e84f` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_bf17cacc5246d32bbb2f` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000)) as `sub` order by `updated_at` desc limit 10 offset 0) {"userId":11,"email":"hayashi1.tomonori@nihon-tesco.co.jp","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'order clause' (SQL: select `id` from ((select `id` from `exm__5ce761f4dfcbf63010e9` where 0 = 1 and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_c47ed046ac8504d59a44` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_2137450de3bf41f9f06d` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_fb5fa64105453e89b3a0` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_7aac560f5062dd08e6d4` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_0cd0a0c5b21930e5e26b` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_7ba5838c9db1d8d5e84f` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000) union (select `id` from `exm__5ce761f4dfcbf63010e9` where `column_bf17cacc5246d32bbb2f` LIKE %PC% and (`column_2137450de3bf41f9f06d` LIKE %PC% and ((`column_7ba5838c9db1d8d5e84f` LIKE [%] and JSON_SEARCH(column_7ba5838c9db1d8d5e84f, 'one', '廃棄') is null) or (`column_7ba5838c9db1d8d5e84f` NOT LIKE [%] and `column_7ba5838c9db1d8d5e84f` <> 廃棄))) and `exm__5ce761f4dfcbf63010e9`.`deleted_at` is null limit 1000)) as `sub` order by `updated_at` desc limit 10 offset 0) at /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'order clause' at /var/www/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'order clause' at /var/www/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)
[stacktrace]
#0 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `id` fro...', Array, Object(Closure))
#1 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select `id` fro...', Array, Object(Closure))
#2 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1963): Illuminate\\Database\\Connection->select('select `id` fro...', Array, true)
#3 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1951): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2435): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1952): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1982): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /var/www/exment/vendor/exceedone/exment/src/Model/CustomTable.php(1196): Illuminate\\Database\\Query\\Builder->paginate(10)
#8 /var/www/exment/vendor/exceedone/exment/src/Controllers/ApiDataController.php(187): Exceedone\\Exment\\Model\\CustomTable->searchValue('PC', Array)
#9 /var/www/exment/vendor/exceedone/exment/src/Controllers/ApiDataController.php(100): Exceedone\\Exment\\Controllers\\ApiDataController->executeQuery(Object(Illuminate\\Http\\Request), 10)
#10 [internal function]: Exceedone\\Exment\\Controllers\\ApiDataController->dataSelect(Object(Illuminate\\Http\\Request), 'asset_table')
#11 /var/www/exment/vendor/exceedone/exment/src/Controllers/ApiDataController.php(47): call_user_func_array(Array, Array)
#12 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Exceedone\\Exment\\Controllers\\ApiDataController->callAction('dataSelect', Array)
#13 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Exceedone\\Exment\\Controllers\\ApiDataController), 'dataSelect')
#14 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#15 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#16 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\LogOperation->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\Morph->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/exment/vendor/exceedone/exment/src/Middleware/AuthenticateApi.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\AuthenticateApi->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\\Exment\\Middleware\\IpFilterBase->handleBase(Object(Illuminate\\Http\\Request), Object(Closure), 'web_ip_filters')
#28 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\\Exment\\Middleware\\WebIPFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#50 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#51 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#52 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#53 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#54 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/exment/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#72 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#73 /var/www/exment/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#74 {main}

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

子テーブルのデータ一覧からレコードを変更無しで更新した場合はエラーは発生しません。
親子テーブルを同時に表示するフォームの場合に、子テーブルにユニーク属性のカラムがあるとエラーになります。

環境が最新バージョンではないので、既に改修済みでしたらcloseさせて頂きます。

**Comment by dev-hayash** [comment]
v3.6.6でも発生する事を確認しました。

**Comment by hirossyi73** [comment]
こちら、関連ライブラリの修正も必要な、かなり複雑な修正となります。お時間かかります、恐縮ですがお待ちいただけますよう、よろしくお願いします。

**Comment by dev-hayash** [comment]
御確認頂きありがとうございます。
了解です。
